apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: recruitflow-backend-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - recruitflow
  selector:
    matchLabels:
      app: recruitflow-backend
  endpoints:
    - port: http
      path: /metrics
      interval: 15s