apiVersion: v1
kind: Service
metadata:
  name: recruitflow-backend
  namespace: recruitflow
spec:
  type: LoadBalancer
  selector:
    app: recruitflow-backend
  ports:
    - port: 5000
      targetPort: 5000
